export const types = {
    REGISTER_SUCCESS : 'REGISTER_SUCCESS',
    REGISTER_FAIL : 'REGISTER_FAIL',
    LOGIN_SUCCESS : 'LOGIN_SUCCESS',
    LOGIN_FAIL : 'LOGIN_FAIL',
    LOGOUT : 'LOGOUT',
    USER_LOADED : 'USER_LOADED',
    AUTH_ERROR : 'AUTH_ERROR',
    CLEAR_ERRORS : 'CLEAR_ERRORS',
} 